### ISSUE TITLE
add config file

### ISSUE THREAD

**Issue by suurajroshan** [khdlr/COBRA#1]
I'm trying to use your code for a similar application and would really appreciate if you could upload the config file or any file that I can use to replicate the environment.

**Comment by khdlr** [comment]
Hi mate, you caught me on vacation so please excuse the late reply!

I just pushed I `pyproject.toml` (https://github.com/khdlr/COBRA/blob/master/pyproject.toml), that can be used to run the project with [rye](https://rye.astral.sh/). Also updated some code in the package slightly to work with the newest versions of everything.

Let me know if you have additional questions! :)

Cheers
Konrad
